using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable UnusedMember.Local
namespace HobbitES.Messages.Commands
{
    #region Generated by Lokad Code DSL
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class RegisterPlayer : ICommand
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        [DataMember(Order = 2)] public string PlayerId { get; private set; }
        
        RegisterPlayer () {}
        public RegisterPlayer (Guid id, string playerId)
        {
            Id = id;
            PlayerId = playerId;
        }
        
        public override string ToString()
        {
            return string.Format(@"RegisterPlayer: ID: {0}, PlayerID: {1}", Id, PlayerId);
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class JoinGame : ICommand
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        [DataMember(Order = 2)] public Guid PlayerId { get; private set; }
        
        JoinGame () {}
        public JoinGame (Guid id, Guid playerId)
        {
            Id = id;
            PlayerId = playerId;
        }
        
        public override string ToString()
        {
            return string.Format(@"JoinGame: ID: {0}, PlayerID: {1}", Id, PlayerId);
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class BuildCity : ICommand
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        [DataMember(Order = 2)] public Guid PlayerId { get; private set; }
        [DataMember(Order = 3)] public Guid ProvinceId { get; private set; }
        [DataMember(Order = 4)] public int X { get; private set; }
        [DataMember(Order = 5)] public int Y { get; private set; }
        
        BuildCity () {}
        public BuildCity (Guid id, Guid playerId, Guid provinceId, int x, int y)
        {
            Id = id;
            PlayerId = playerId;
            ProvinceId = provinceId;
            X = x;
            Y = y;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class StartBuilding : ICommand
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        StartBuilding () {}
        public StartBuilding (Guid id)
        {
            Id = id;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class StartResearch : ICommand
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        StartResearch () {}
        public StartResearch (Guid id)
        {
            Id = id;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class TrainTroops : ICommand
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        TrainTroops () {}
        public TrainTroops (Guid id)
        {
            Id = id;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class TrainDefenses : ICommand
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        TrainDefenses () {}
        public TrainDefenses (Guid id)
        {
            Id = id;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class ChangeTaxRate : ICommand
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        ChangeTaxRate () {}
        public ChangeTaxRate (Guid id)
        {
            Id = id;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class UseItem : ICommand
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        UseItem () {}
        public UseItem (Guid id)
        {
            Id = id;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class CollectQuestReward : ICommand
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        CollectQuestReward () {}
        public CollectQuestReward (Guid id)
        {
            Id = id;
        }
    }
    #endregion
}
