using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable UnusedMember.Local
namespace HobbitES.Messages.Events
{
    #region Generated by Lokad Code DSL
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class PlayerRegistered : IEvent
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        [DataMember(Order = 2)] public string PlayerId { get; private set; }
        
        PlayerRegistered () {}
        public PlayerRegistered (Guid id, string playerId)
        {
            Id = id;
            PlayerId = playerId;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class JoinedGame : IEvent
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        [DataMember(Order = 2)] public Guid PlayerId { get; private set; }
        [DataMember(Order = 3)] public Guid GameId { get; private set; }
        
        JoinedGame () {}
        public JoinedGame (Guid id, Guid playerId, Guid gameId)
        {
            Id = id;
            PlayerId = playerId;
            GameId = gameId;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class CityBuilt : IEvent
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        [DataMember(Order = 2)] public Guid PlayerId { get; private set; }
        [DataMember(Order = 3)] public Guid ProvinceId { get; private set; }
        [DataMember(Order = 4)] public int X { get; private set; }
        [DataMember(Order = 5)] public int Y { get; private set; }
        
        CityBuilt () {}
        public CityBuilt (Guid id, Guid playerId, Guid provinceId, int x, int y)
        {
            Id = id;
            PlayerId = playerId;
            ProvinceId = provinceId;
            X = x;
            Y = y;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class BuildingStarted : IEvent
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        BuildingStarted () {}
        public BuildingStarted (Guid id)
        {
            Id = id;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class BuildingCompleted : IEvent
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        BuildingCompleted () {}
        public BuildingCompleted (Guid id)
        {
            Id = id;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class ResearchStarted : IEvent
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        ResearchStarted () {}
        public ResearchStarted (Guid id)
        {
            Id = id;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class ResearchCompleted : IEvent
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        ResearchCompleted () {}
        public ResearchCompleted (Guid id)
        {
            Id = id;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class TroopsTrained : IEvent
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        TroopsTrained () {}
        public TroopsTrained (Guid id)
        {
            Id = id;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class DefensesTrained : IEvent
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        DefensesTrained () {}
        public DefensesTrained (Guid id)
        {
            Id = id;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class PopulationLimitChanged : IEvent
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        PopulationLimitChanged () {}
        public PopulationLimitChanged (Guid id)
        {
            Id = id;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class TotalPopulationChanged : IEvent
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        TotalPopulationChanged () {}
        public TotalPopulationChanged (Guid id)
        {
            Id = id;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class IdlePopulationChanged : IEvent
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        IdlePopulationChanged () {}
        public IdlePopulationChanged (Guid id)
        {
            Id = id;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class ResourcesGenerated : IEvent
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        ResourcesGenerated () {}
        public ResourcesGenerated (Guid id)
        {
            Id = id;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class BaseFoodProductionChanged : IEvent
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        BaseFoodProductionChanged () {}
        public BaseFoodProductionChanged (Guid id)
        {
            Id = id;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class BaseWoodProductionChanged : IEvent
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        BaseWoodProductionChanged () {}
        public BaseWoodProductionChanged (Guid id)
        {
            Id = id;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class BaseStoneProductionChanged : IEvent
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        BaseStoneProductionChanged () {}
        public BaseStoneProductionChanged (Guid id)
        {
            Id = id;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class BaseOreProductionChanged : IEvent
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        BaseOreProductionChanged () {}
        public BaseOreProductionChanged (Guid id)
        {
            Id = id;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class BaseGoldProductionChanged : IEvent
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        BaseGoldProductionChanged () {}
        public BaseGoldProductionChanged (Guid id)
        {
            Id = id;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class TaxRateChanged : IEvent
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        TaxRateChanged () {}
        public TaxRateChanged (Guid id)
        {
            Id = id;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class ItemAcquired : IEvent
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        ItemAcquired () {}
        public ItemAcquired (Guid id)
        {
            Id = id;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class QuestRewardCollected : IEvent
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        QuestRewardCollected () {}
        public QuestRewardCollected (Guid id)
        {
            Id = id;
        }
    }
    
        
    
    [DataContract(Namespace = "HobbitES.Messages")]
    public partial class PlayerMightChanged : IEvent
    {
        [DataMember(Order = 1)] public Guid Id { get; private set; }
        
        PlayerMightChanged () {}
        public PlayerMightChanged (Guid id)
        {
            Id = id;
        }
    }
    #endregion
}
